name: "Nightly Run"

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
  pre-release:
    name: "Nightly Run"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Update 'nightly' tag"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Nightly build"
