name: "Nightly Run"

on:
  schedule:
      - cron: "0 0 * * *"

jobs:
  pre-release:
    name: "Nightly Run"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Naev Repository
        uses: actions/checkout@v2

      - name: "Update 'nightly' release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: false
          title: "Nightly build"
          files: |
            *.spec
